# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
    - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Get the version/tag
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        
      # Makes a copy of the STS Global Test Data Management.pdf to be included in the deployment files for the release.
      - name: copy documentation file
        run: cp STS\ Global\ Test\ Data\ Management.pdf GlobalTestData/GlobalTestData-ReadMe.pdf
        
      # Zip up files to be deployed as part of the release materials.
      - name: copy documentation file
        run: zip -qq -r GlobalTestData_v${{ steps.tagName.outputs.tag }}.zip GlobalTestData
          
      # Uploads the release materials as build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: GlobalTestData.zip
          path: GlobalTestData_v${{ steps.tagName.outputs.tag }}.zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: GlobalTestData.zip
